### ISSUE TITLE
On Mac : Your browser version is no longer supported. Some things may not display correctly.

### ISSUE THREAD

**Issue by goguzo** [mituoh/Dropbox-Paper-Mac#3]
I get the message "Your browser version is no longer supported. Some things may not display correctly." on top of the app on mac. My default browser is Safari 10.0.2. It works nicely though. How can I get rid of this message?

**Comment by mituoh** [comment]
Hi! Thanks for your reporting.
I fixed it with the latest version.

**Comment by goguzo** [comment]
Thanks a lot. I’ll try now.
